
export const SIGNUP_URL = "http://localhost:8000/api/v1/user/register"
export const LOGIN_URL = "http://localhost:8000/api/v1/user/login"
export const LOGOUT_URL = "http://localhost:8000/api/v1/user/logout"
export const NEWPOST_URL = "http://localhost:8000/api/v1/post/newpost"
export const GETPOSTS_URL = "http://localhost:8000/api/v1/post/posts"
export const DELETE_POST_URL = "http://localhost:8000/api/v1/post/delete/"
export const LIKE_POST_URL = "http://localhost:8000/api/v1/post/"
export const ADDD_COMMENT_URL = "http://localhost:8000/api/v1/post/" 
export const SUGGESTED_USER_URL = "http://localhost:8000/api/v1/user/suggested"
export const USER_PROFILE_URL = "http://localhost:8000/api/v1/user/"
export const EDIT_PROFILE_URL = "http://localhost:8000/api/v1/user/profile/edit"
export const SEND_MSG_URL = "http://localhost:8000/api/v1/message/send"
export const GET_ALL_MSG_URL = "http://localhost:8000/api/v1/message/allmessages"
export const BOOKMARK_POST_URL = "http://localhost:8000/api/v1/post/"